apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    configmanagement.gke.io/cluster-selector: selector-workloads
spec:
  selector:
    matchLabels:
      app: api
  minReadySeconds: 0
  replicas: 3
  template:
    spec:
      containers:
      - name: api
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            memory: "256M"
            cpu: "150m"
          limits:
            memory: "1G"
            cpu: "300m"
      terminationGracePeriodSeconds: 30