apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    configmanagement.gke.io/cluster-selector: selector-workloads
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 8080